/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedFilaRouteImport } from './routes/_authenticated/fila'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChamadosIndexRouteImport } from './routes/_authenticated/chamados.index'
import { Route as AuthenticatedBaseConhecimentoIndexRouteImport } from './routes/_authenticated/base-conhecimento.index'
import { Route as AuthenticatedChamadosNovoRouteImport } from './routes/_authenticated/chamados.novo'
import { Route as AuthenticatedChamadosIdRouteImport } from './routes/_authenticated/chamados.$id'
import { Route as AuthenticatedBaseConhecimentoNovoRouteImport } from './routes/_authenticated/base-conhecimento.novo'
import { Route as AuthenticatedBaseConhecimentoIdRouteImport } from './routes/_authenticated/base-conhecimento.$id'
import { Route as AuthenticatedBaseConhecimentoIdEditarRouteImport } from './routes/_authenticated/base-conhecimento.$id.editar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFilaRoute = AuthenticatedFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChamadosIndexRoute =
  AuthenticatedChamadosIndexRouteImport.update({
    id: '/chamados/',
    path: '/chamados/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBaseConhecimentoIndexRoute =
  AuthenticatedBaseConhecimentoIndexRouteImport.update({
    id: '/base-conhecimento/',
    path: '/base-conhecimento/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChamadosNovoRoute =
  AuthenticatedChamadosNovoRouteImport.update({
    id: '/chamados/novo',
    path: '/chamados/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChamadosIdRoute = AuthenticatedChamadosIdRouteImport.update({
  id: '/chamados/$id',
  path: '/chamados/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBaseConhecimentoNovoRoute =
  AuthenticatedBaseConhecimentoNovoRouteImport.update({
    id: '/base-conhecimento/novo',
    path: '/base-conhecimento/novo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBaseConhecimentoIdRoute =
  AuthenticatedBaseConhecimentoIdRouteImport.update({
    id: '/base-conhecimento/$id',
    path: '/base-conhecimento/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBaseConhecimentoIdEditarRoute =
  AuthenticatedBaseConhecimentoIdEditarRouteImport.update({
    id: '/editar',
    path: '/editar',
    getParentRoute: () => AuthenticatedBaseConhecimentoIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/base-conhecimento/$id': typeof AuthenticatedBaseConhecimentoIdRouteWithChildren
  '/base-conhecimento/novo': typeof AuthenticatedBaseConhecimentoNovoRoute
  '/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/chamados/novo': typeof AuthenticatedChamadosNovoRoute
  '/base-conhecimento/': typeof AuthenticatedBaseConhecimentoIndexRoute
  '/chamados/': typeof AuthenticatedChamadosIndexRoute
  '/base-conhecimento/$id/editar': typeof AuthenticatedBaseConhecimentoIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/base-conhecimento/$id': typeof AuthenticatedBaseConhecimentoIdRouteWithChildren
  '/base-conhecimento/novo': typeof AuthenticatedBaseConhecimentoNovoRoute
  '/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/chamados/novo': typeof AuthenticatedChamadosNovoRoute
  '/base-conhecimento': typeof AuthenticatedBaseConhecimentoIndexRoute
  '/chamados': typeof AuthenticatedChamadosIndexRoute
  '/base-conhecimento/$id/editar': typeof AuthenticatedBaseConhecimentoIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fila': typeof AuthenticatedFilaRoute
  '/_authenticated/base-conhecimento/$id': typeof AuthenticatedBaseConhecimentoIdRouteWithChildren
  '/_authenticated/base-conhecimento/novo': typeof AuthenticatedBaseConhecimentoNovoRoute
  '/_authenticated/chamados/$id': typeof AuthenticatedChamadosIdRoute
  '/_authenticated/chamados/novo': typeof AuthenticatedChamadosNovoRoute
  '/_authenticated/base-conhecimento/': typeof AuthenticatedBaseConhecimentoIndexRoute
  '/_authenticated/chamados/': typeof AuthenticatedChamadosIndexRoute
  '/_authenticated/base-conhecimento/$id/editar': typeof AuthenticatedBaseConhecimentoIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/fila'
    | '/base-conhecimento/$id'
    | '/base-conhecimento/novo'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/base-conhecimento/'
    | '/chamados/'
    | '/base-conhecimento/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/fila'
    | '/base-conhecimento/$id'
    | '/base-conhecimento/novo'
    | '/chamados/$id'
    | '/chamados/novo'
    | '/base-conhecimento'
    | '/chamados'
    | '/base-conhecimento/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/fila'
    | '/_authenticated/base-conhecimento/$id'
    | '/_authenticated/base-conhecimento/novo'
    | '/_authenticated/chamados/$id'
    | '/_authenticated/chamados/novo'
    | '/_authenticated/base-conhecimento/'
    | '/_authenticated/chamados/'
    | '/_authenticated/base-conhecimento/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fila': {
      id: '/_authenticated/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof AuthenticatedFilaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamados/': {
      id: '/_authenticated/chamados/'
      path: '/chamados'
      fullPath: '/chamados/'
      preLoaderRoute: typeof AuthenticatedChamadosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento/': {
      id: '/_authenticated/base-conhecimento/'
      path: '/base-conhecimento'
      fullPath: '/base-conhecimento/'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamados/novo': {
      id: '/_authenticated/chamados/novo'
      path: '/chamados/novo'
      fullPath: '/chamados/novo'
      preLoaderRoute: typeof AuthenticatedChamadosNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamados/$id': {
      id: '/_authenticated/chamados/$id'
      path: '/chamados/$id'
      fullPath: '/chamados/$id'
      preLoaderRoute: typeof AuthenticatedChamadosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento/novo': {
      id: '/_authenticated/base-conhecimento/novo'
      path: '/base-conhecimento/novo'
      fullPath: '/base-conhecimento/novo'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento/$id': {
      id: '/_authenticated/base-conhecimento/$id'
      path: '/base-conhecimento/$id'
      fullPath: '/base-conhecimento/$id'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/base-conhecimento/$id/editar': {
      id: '/_authenticated/base-conhecimento/$id/editar'
      path: '/editar'
      fullPath: '/base-conhecimento/$id/editar'
      preLoaderRoute: typeof AuthenticatedBaseConhecimentoIdEditarRouteImport
      parentRoute: typeof AuthenticatedBaseConhecimentoIdRoute
    }
  }
}

interface AuthenticatedBaseConhecimentoIdRouteChildren {
  AuthenticatedBaseConhecimentoIdEditarRoute: typeof AuthenticatedBaseConhecimentoIdEditarRoute
}

const AuthenticatedBaseConhecimentoIdRouteChildren: AuthenticatedBaseConhecimentoIdRouteChildren =
  {
    AuthenticatedBaseConhecimentoIdEditarRoute:
      AuthenticatedBaseConhecimentoIdEditarRoute,
  }

const AuthenticatedBaseConhecimentoIdRouteWithChildren =
  AuthenticatedBaseConhecimentoIdRoute._addFileChildren(
    AuthenticatedBaseConhecimentoIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFilaRoute: typeof AuthenticatedFilaRoute
  AuthenticatedBaseConhecimentoIdRoute: typeof AuthenticatedBaseConhecimentoIdRouteWithChildren
  AuthenticatedBaseConhecimentoNovoRoute: typeof AuthenticatedBaseConhecimentoNovoRoute
  AuthenticatedChamadosIdRoute: typeof AuthenticatedChamadosIdRoute
  AuthenticatedChamadosNovoRoute: typeof AuthenticatedChamadosNovoRoute
  AuthenticatedBaseConhecimentoIndexRoute: typeof AuthenticatedBaseConhecimentoIndexRoute
  AuthenticatedChamadosIndexRoute: typeof AuthenticatedChamadosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFilaRoute: AuthenticatedFilaRoute,
  AuthenticatedBaseConhecimentoIdRoute:
    AuthenticatedBaseConhecimentoIdRouteWithChildren,
  AuthenticatedBaseConhecimentoNovoRoute:
    AuthenticatedBaseConhecimentoNovoRoute,
  AuthenticatedChamadosIdRoute: AuthenticatedChamadosIdRoute,
  AuthenticatedChamadosNovoRoute: AuthenticatedChamadosNovoRoute,
  AuthenticatedBaseConhecimentoIndexRoute:
    AuthenticatedBaseConhecimentoIndexRoute,
  AuthenticatedChamadosIndexRoute: AuthenticatedChamadosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
